use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
#[serde(default)]
pub struct PaddleOcrModelConfig {
    pub det_model_dir: String,
    pub rec_model_dir: String,
    pub doc_orientation_model_name: Option<String>,
    pub doc_orientation_model_dir: Option<String>,
    pub doc_unwarping_model_name: Option<String>,
    pub doc_unwarping_model_dir: Option<String>,
    pub text_detection_model_name: Option<String>,
    pub text_recognition_model_name: Option<String>,
    pub textline_orientation_model_name: Option<String>,
    pub textline_orientation_model_dir: Option<String>,
    pub textline_orientation_batch_size: Option<i32>,
    pub text_recognition_batch_size: Option<i32>,
    pub use_doc_orientation_classify: Option<bool>,
    pub use_doc_unwarping: Option<bool>,
    pub use_textline_orientation: Option<bool>,
    pub text_det_limit_side_len: Option<i32>,
    pub text_det_max_side_limit: Option<i32>,
    pub text_det_limit_type: Option<String>,
    pub text_det_thresh: Option<f32>,
    pub text_det_box_thresh: Option<f32>,
    pub text_det_unclip_ratio: Option<f32>,
    pub text_rec_score_thresh: Option<f32>,
    pub text_det_input_shape: Option<Vec<i32>>,
    pub text_rec_input_shape: Option<Vec<i32>>,
    pub lang: Option<String>,
    pub ocr_version: Option<String>,
    pub vis_font_dir: Option<String>,
    pub device: Option<String>,
    pub precision: Option<String>,
    pub enable_mkldnn: Option<bool>,
    pub mkldnn_cache_capacity: Option<i32>,
    pub cpu_threads: Option<i32>,
    pub thread_num: Option<i32>,
    pub paddlex_config_yaml: Option<String>,
}

impl Default for PaddleOcrModelConfig {
    fn default() -> Self {
        Self {
            det_model_dir: String::new(),
            rec_model_dir: String::new(),
            doc_orientation_model_name: None,
            doc_orientation_model_dir: None,
            doc_unwarping_model_name: None,
            doc_unwarping_model_dir: None,
            text_detection_model_name: None,
            text_recognition_model_name: None,
            textline_orientation_model_name: None,
            textline_orientation_model_dir: None,
            textline_orientation_batch_size: None,
            text_recognition_batch_size: None,
            use_doc_orientation_classify: Some(false),
            use_doc_unwarping: Some(false),
            use_textline_orientation: Some(false),
            text_det_limit_side_len: None,
            text_det_max_side_limit: None,
            text_det_limit_type: None,
            text_det_thresh: None,
            text_det_box_thresh: None,
            text_det_unclip_ratio: None,
            text_rec_score_thresh: None,
            text_det_input_shape: None,
            text_rec_input_shape: None,
            lang: None,
            ocr_version: None,
            vis_font_dir: None,
            device: Some("cpu".to_string()),
            precision: Some("fp32".to_string()),
            enable_mkldnn: Some(true),
            mkldnn_cache_capacity: Some(10),
            cpu_threads: Some(8),
            thread_num: Some(1),
            paddlex_config_yaml: None,
        }
    }
}
